version: '3'

services:
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILE_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT = configserver:http://configserver:8071"