spring:
  application:
    name: organization-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://configserver:8071

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    ru.aasmc: DEBUG
